services:
  water-monitor:
    image: ghcr.io/jteijema/waterpijl:latest
    container_name: water_monitor
    restart: unless-stopped
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - ALERT_LEVEL=${ALERT_LEVEL}
      - LOCATION_CODE=${LOCATION_CODE}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
